django/academy/core/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accounts.views import UserRegistrationView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('structure.urls')),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

django/academy/structure/urls.py
from django.urls import path

from structure.models import Faculty, Department
from structure.views import IndexView, FacultyView, DepartmentView


urlpatterns = [
    path('', IndexView.as_view(), name='main'),
] + [
    path(
        f'{faculty.acronym}/',
        FacultyView.as_view(),
        kwargs={'pk': faculty.id},
        name=f'{faculty.acronym}'
    )
    for faculty in Faculty.objects.all()
] + [
    path(
        f'{dep.acronym}/',
        DepartmentView.as_view(),
        kwargs={'pk': dep.id},
        name=f'{dep.acronym}'
    )
    for dep in Department.objects.all()
] + []

django/academy/structure/models.py
from django.db import models

from structure import fields


class AcronymMixin:
    """
    Класс-примесь для моделей с атрибутом name.
    """
    @property
    def acronym(self):
        return ''.join(
            word[0]
            for word in str(self.name).lower().split()
            if len(word) > 3
        )

    def get_breadcrumb(self):
        previous = []
        for field in self._meta.get_fields():
            if field.__class__ is models.ForeignKey:
                parent = getattr(self, field.name)
                previous = parent.get_foreign() + [{'name': parent.name, 'url': parent.acronym}]
        return previous


class Faculty(models.Model, AcronymMixin):
    id = fields.PositiveTinyAutoField(primary_key=True)
    financing = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'faculties'

    def __str__(self):
        return f'{self.name}'


class Department(models.Model, AcronymMixin):
    id = models.SmallAutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    building = models.IntegerField()
    financing = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0
    )
    faculty = models.ForeignKey(Faculty, models.CASCADE)

    class Meta:
        db_table = 'departments'

    def __str__(self):
        return f'{self.name}'


class Curator(models.Model):
    id = fields.PositiveMediumAutoField(primary_key=True)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)

    class Meta:
        db_table = 'curators'

    def __str__(self):
        return f'{self.name} {self.surname}'



class Subject(models.Model):
    id = models.SmallAutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'subjects'

    def __str__(self):
        return f'{self.name}'


class Teacher(models.Model):
    id = models.SmallAutoField(primary_key=True)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    salary = models.DecimalField(
        max_digits=8,
        decimal_places=2
    )
    is_professor = models.BooleanField(default=0)
    subjects = models.ManyToManyField(
        Subject,
        through='Lecture',
    )

    class Meta:
        db_table = 'teachers'

    def __str__(self):
        return f'{self.name} {self.surname}'


class Lecture(models.Model):
    date = models.DateField()
    subject = models.ForeignKey(Subject, models.CASCADE)
    teacher = models.ForeignKey(Teacher, models.CASCADE)

    class Meta:
        db_table = 'lectures'

    def __str__(self):
        return f'{self.date} — {self.subject} ({self.teacher})'


class Student(models.Model):
    id = fields.PositiveMediumAutoField(primary_key=True)
    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    rating = models.IntegerField()

    class Meta:
        db_table = 'students'

    def __str__(self):
        return f'{self.name} {self.surname}'


class Group(models.Model, AcronymMixin):
    id = fields.PositiveMediumAutoField(primary_key=True)
    name = models.CharField(max_length=10, unique=True)
    year = models.IntegerField()
    department = models.ForeignKey(Department, models.CASCADE)
    students = models.ManyToManyField(Student, db_table='groups_students')
    lectures = models.ManyToManyField(Lecture, db_table='groups_lectures')
    curators = models.ManyToManyField(Curator, db_table='groups_curators')

    class Meta:
        db_table = 'groups'
        ordering = ['year', 'name']

    def __str__(self):
        return f'({self.year}) {self.name}'

django/academy/structure/forms.py
from decimal import Decimal as dec
from django import forms

from structure.models import Department, Group


class AddDepartment(forms.ModelForm):
    select_currency = forms.ChoiceField(choices=(
        ('USD', 'USD'),
        ('EUR', 'EUR'),
    ))

    class Meta:
        model = Department
        fields = ('name', 'building', 'financing')
        # exclude = ('faculty',)
        labels = {
            'name': 'Enter the name for a new department',
            'building': 'Enter the building number for a new department',
            'financing': 'Enter the current budget for a new department',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs |= {'class': 'form-control'}
        self.fields['building'].widget.attrs |= {'class': 'form-control'}
        self.fields['financing'].widget.attrs |= {'class': 'form-control'}
        self.fields['select_currency'].widget.attrs |= {'class': 'btn btn-outline-secondary dropdown-toggle'}

    def save_with_fk(self, faculty):
        department = super().save(commit=False)
        department.faculty = faculty
        if self.cleaned_data['select_currency'] == 'EUR':
            department.financing *= dec('0.85')
        department.save()
        return department


class AddGroup(forms.ModelForm):
    year = forms.IntegerField(
        min_value=1,
        max_value=6,
        label='Enter the current year of education for a new group'
    )

    class Meta:
        model = Group
        fields = ('year', 'name')
        labels = {
            'name': 'Enter the name for a new group',
        }

    def save_with_fk(self, department):
        group = super().save(commit=False)
        group.department = department
        group.save()
        return group

django/academy/structure/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin

from structure.forms import AddDepartment, AddGroup
from structure.models import Faculty, Department


# faculty_menu = {
#     faculty.acronym: [
#         {'name': 'Head', 'url': f'/{faculty.acronym}/head/'},
#         {'name': 'Departments', 'url': f'/{faculty.acronym}/departments/'},
#         {'name': 'Science', 'url': f'/{faculty.acronym}/science/'},
#     ]
#     for faculty in Faculty.objects.all()
# }

# department_menu = (
#     {'name': 'Head', 'url': 'head/'},
#     {'name': 'Teachers', 'url': 'teachers/'},
#     {'name': 'Groups', 'url': 'groups/'},
#     {'name': 'Programs', 'url': 'programs/'},
# )


class IndexView(ListView):
    model = Faculty
    template_name = 'structure/index.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        return {
            'base_template': 'bs_base.html',
        } | super().get_context_data(object_list=object_list, **kwargs)


class FacultyView(View):

    def get(self, request, *args, **kwargs):
        view = FacultyDetails.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = FacultyAddDepartment.as_view()
        return view(request, *args, **kwargs)


class FacultyDetails(DetailView):
    model = Faculty
    template_name = 'structure/faculty.html'

    def get_context_data(self, **kwargs):
        return {
            'base_template': 'bs_base.html',
            'page_title': self.object.acronym.upper(),
            'form': AddDepartment(),
            # 'top_menu': faculty_menu[self.object.acronym],
        } | super().get_context_data(**kwargs)


class FacultyAddDepartment(SingleObjectMixin, FormView):
    model = Faculty
    form_class = AddDepartment
    template_name = 'structure/faculty.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.save_with_fk(self.object)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(self.object.acronym, kwargs={'pk': self.object.pk})


# простая альтернатива для простой логики обработки HTTP запроса
# def faculty_view(request, pk: int):
#     model = Faculty.objects.get(pk=pk)
#
#     if request.model == 'GET':
#         form = AddDepartment()
#
#     elif request.model == 'POST':
#         form = AddDepartment(request.POST)
#         if form.is_valid():
#             form.save_with_fk(model)
#             url = reverse(model.acronym, kwargs={'pk': model.pk})
#             return redirect(url)
#
#     return render(
#         request, 'structure/faculty.html',
#         {
#             'page_title': model.acronym.upper(),
#             'object': model,
#             'form': form,
#         }
#     )


class DepartmentView(View):

    def get(self, request, *args, **kwargs):
        view = DepartmentDetails.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = DepartmentAddGroup.as_view()
        return view(request, *args, **kwargs)


class DepartmentDetails(LoginRequiredMixin, DetailView):
    model = Department
    template_name = 'structure/department.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        return {
            'base_template': 'bs_base.html',
            'page_title': self.object.acronym.upper(),
            'form': AddGroup(),
        } | super().get_context_data(object_list=object_list, **kwargs)


class DepartmentAddGroup(SingleObjectMixin, FormView):
    model = Department
    form_class = AddGroup
    template_name = 'structure/department.html'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.save_with_fk(self.object)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(self.object.acronym, kwargs={'pk': self.object.pk})

django/academy/structure/templates/structure/department.html
{% extends base_template|default:"base.html" %}

{% load bootstrap5 %}
{% load user_tags %}


{% block base_content %}

  <div class="container">
    <div class="row">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          {% for item in object.get_breadcrumb %}
            <li class="breadcrumb-item"><a href="{% url item.url %}">{{ item.name }}</a></li>
          {% endfor %}
          <li class="breadcrumb-item active" aria-current="page">{{ object }}</li>
        </ol>
      </nav>
    </div>
    <br>
    <div class="row">
      <h4 class="display-4">{{ object }}</h4>
    </div>
    <br>
    <div class="row">
      <h5>Building: {{ object.building }}</h5>
    </div>
    <br>
    <div class="row">
      <h5>Financing: {{ object.financing|floatformat:"2g" }} ₽</h5>
    </div>
    <br>
    <div class="row">
      <h6 class="display-6">Groups</h6>
      {% if object.group_set.all %}
        <table cellpadding="3">
          {% for group in object.group_set.all %}
            <tr>
              <td>{{ group }}</td>
            </tr>
          {% endfor %}
        </table>
      {% endif %}
    </div>
    {% has_perm 'structure.add_group' as add_form_perm %}
    {% if add_form_perm %}
      <br>
      <div class="row">
        <h6 class="display-6">Add group</h6>
        <form action="" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="mb-3">
            {% bootstrap_button 'Add' button_type='submit' button_class='btn-warning' size='lg' %}
          </div>
        </form>
      </div>
    {% endif %}
  </div>

{% endblock base_content %}

django/academy/structure/templates/structure/faculty.html
{% extends base_template|default:"base.html" %}

<!--suppress XmlInvalidId -->
{% load bootstrap5 %}
{% load user_tags %}


{% block base_content %}

  <div class="accordion monokai_pro"
       id="accordionExample">
    {% if object.department_set.all %}
      <div class="accordion-item monokai_pro">
        <h2 class="accordion-header monokai_pro"
            id="headingOne">
          <button class="accordion-button monokai_pro"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapseOne"
                  aria-expanded="true"
                  aria-controls="collapseOne">
            Departments:
          </button>
        </h2>
        <div id="collapseOne"
             class="accordion-collapse collapse show monokai_pro"
             aria-labelledby="headingOne"
             data-bs-parent="#accordionExample">
          <div class="accordion-body monokai_pro">
            <table cellpadding="4">
              {% for department in object.department_set.all %}
                <tr>
                  <td>
                    <a href="{% url department.acronym %}">{{ department }}</a>
                  </td>
                </tr>
              {% endfor %}
            </table>
          </div>
        </div>
      </div>
    {% endif %}

    <div class="accordion-item monokai_pro">
      <h2 class="accordion-header monokai_pro"
          id="headingTwo">
        <button class="accordion-button collapsed monokai_pro"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseTwo"
                aria-expanded="false"
                aria-controls="collapseTwo">
          Financing:
        </button>
      </h2>
      <div id="collapseTwo"
           class="accordion-collapse collapse monokai_pro"
           aria-labelledby="headingTwo"
           data-bs-parent="#accordionExample">
        <div class="accordion-body monokai_pro">
          {{ object.financing|floatformat:"2g" }} ₽
        </div>
      </div>
    </div>

    {% has_perm 'structure.add_department' as add_form_perm %}
    {% if add_form_perm %}
      <div class="accordion-item monokai_pro">
        <h2 class="accordion-header monokai_pro"
            id="headingThree">
          <button class="accordion-button collapsed monokai_pro"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#collapseThree"
                  aria-expanded="false"
                  aria-controls="collapseThree">
            Add Department
          </button>
        </h2>
        <div id="collapseThree"
             class="accordion-collapse collapse monokai_pro"
             aria-labelledby="headingThree"
             data-bs-parent="#accordionExample">
          <div class="accordion-body monokai_pro">
            <form action="" method="post">
              {% csrf_token %}

              {% bootstrap_field form.name %}
              {% bootstrap_field form.building %}

              <div class="mb-3">
                <label for="{{ form.financing.id_for_label }}"
                       class="form-label">
                  {{ form.financing.label }}
                </label>
                <div class="input-group mb-3">
                  <input type="text"
                         name="{{ form.financing.name }}"
                         id="{{ form.financing.id }}"
                         class="form-control"
                         value="{{ form.financing.value }}"
                         step="{{ form.financing.step }}">
                  {{ form.select_currency }}
                </div>
              </div>
              <div class="mb-3">
                <input type="submit" value="Add" class="btn btn-primary">
              </div>
            </form>
          </div>
        </div>
      </div>
    {% endif %}
  </div>

{% endblock base_content %}

django/academy/structure/templates/structure/index.html
{% extends base_template|default:"base.html" %}


{% block base_content %}

  <div align="center">
    <h1>ITMO University Structure</h1>
  </div>
  <br>
  <div>
    <table cellpadding="6">
      {% for object in object_list %}
        <tr>
          <td>
            <a href="{% url object.acronym %}">{{ object }}</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>

{% endblock base_content %}